{% set name = "lisc" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lisc-tools/lisc/archive/{{ version }}.tar.gz
  sha256: 66a66de860aa593dbb78356e36325ac7f14495ddeb93b0717aa38956b55a59a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - requests
    - lxml
    - beautifulsoup4
    - nltk

test:
  imports:
    - lisc
    - lisc.analysis
    - lisc.collect
    - lisc.core
    - lisc.data
    - lisc.objects
    - lisc.plts
    - lisc.requester
    - lisc.tests
    - lisc.urls
    - lisc.utils

about:
  home: https://github.com/lisc-tools/lisc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LISC is a package for collecting and analyzing the scientific literature.
  doc_url: https://lisc-tools.github.io/lisc/
  dev_url: https://github.com/lisc-tools/lisc

extra:
  recipe-maintainers:
    - ryanhammonds
